ci/cd:
  - .github/workflows/*

codeowners change:
  - */CODEOWNERS

documentation:
  - README.md
  - ./*.md
  - ./**/Documentation/*
  
performer:
  - Perfomer/**

dispatcher:
  - Dispatcher/**
  
configuration:
  - ./**/Data/Config.xlsx
  - ./**/Framework/InitAllSettings.xaml

framework:
  - ./**/Framework/**
  
templates:
  - ./**/Data/Templates/**

main: 
  - ./**/Main.xaml

process:
  - ./**/Process.xaml
