ci/cd:
  - .github/workflows/*

codeowners change:
  - CODEOWNERS

documentation:
  - README.md
  - ./*.md
  - ./**/Documentation/*
  
performer:
  - Performer/**

dispatcher:
  - Dispatcher/**
  
configuration:
  - ./*/Config.xlsx
  - ./*/Framework/InitAllSettings.xaml

framework:
  - ./**/Framework/**
  
templates:
  - ./*/Data/Templates/**

main: 
  - ./*/Main.xaml

process:
  - ./**/Process.xaml
