ci/cd:
  - .github/workflows/*

codeowners change:
  - CODEOWNERS

documentation:
  - README.md
  - ./*.md
  - ./**/Documentation/*
  
performer:
  - Performer/**

dispatcher:
  - Dispatcher/**
  
configuration:
  - Performer/Data/Config.xlsx
  - Dispatcher/Data/Config.xlsx
  - Performer/Framework/InitAllSettings.xaml
  - Dispatcher/Framework/InitAllSettings.xaml

framework:
  - Performer/Framework/**
  - Dispatcher/Framework/**

templates:
  - Performer/Data/Templates/**

main: 
  - Performer/Main.xaml
  - Dispatcher/Main.xaml

process:
  - Performer/**/Process.xaml
