# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  UIPATH_API_KEY: ${{ secrets.UIPATH_API_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: Mikael-RnD/UiPath-Setup@main
      - uses: Mikael-RnD/UiPath-Pack-Analyze@basic_auth
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/output
          if-no-files-found: error
          retention-days: 90
      
  deploy:
    needs: build
    runs-on: windows-2019
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          # Artifact name
          name: artifact # optional
          # Destination path
          path: ${{github.workspace}} # optional
      
      - uses: Mikael-RnD/UiPath-Setup@main
      - name: UiPath Deploy
        uses: Mikael-RnD/UiPath-Deploy@main
        with:
          orchestratorUrl: https://cloud.uipath.com/hppcntv
          orchestratorFolderPath: "Test"
          orchestratorTenant: Mikaels_RnD
          orchestratorApiKey: $UIPATH_API_KEY
          
